// インスタンスのリソースを提供する.

package resource

import (
	"context"
	"fmt"
	"regexp"
	"time"

	"github.com/gophercloud/gophercloud/v2"

	"github.com/gmo-internet/terraform-provider-conohavps/internal/provider/service"
	"github.com/gophercloud/gophercloud/v2/openstack/compute/v2/servers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &instanceResource{}
var _ resource.ResourceWithImportState = &instanceResource{}

// addressDetailAttrTypes アドレス詳細情報のAttributeType定義.
var addressDetailAttrTypes = map[string]attr.Type{
	"addr":                types.StringType,
	"version":             types.Int64Type,
	"os_ext_ips_type":     types.StringType,
	"os_ext_ips_mac_addr": types.StringType,
}

func NewInstanceResource() resource.Resource {
	return &instanceResource{}
}

type instanceResource struct {
	client *service.ConohaClient
}

// リクエストパラメータ：作成時に指定可能なパラメータのみ.
type instanceResourceModel struct {
	Id              types.String `tfsdk:"id"`                // インスタンスID
	FlavorRef       types.String `tfsdk:"flavor_id"`         // フレーバーID
	BlockDevice     types.List   `tfsdk:"block_device"`      // ブロックデバイスマッピング
	AdminPass       types.String `tfsdk:"admin_pass"`        // 管理者パスワード
	KeyName         types.String `tfsdk:"key_name"`          // SSHキーペア名
	SecurityGroup   types.List   `tfsdk:"security_group"`    // セキュリティグループ
	InstanceNameTag types.String `tfsdk:"instance_name_tag"` // インスタンス名
	UserData        types.String `tfsdk:"user_data"`         // ユーザーデータ
	PowerState      types.String `tfsdk:"power_state"`       // 電源状態
	Status          types.String `tfsdk:"status"`            // インスタンスのステータス
	Addresses       types.Map    `tfsdk:"addresses"`         // ネットワークアドレス
}

// BlockDeviceMappingV2モデル.
type blockDeviceModel struct {
	UUID types.String `tfsdk:"uuid"`
}

// SecurityGroupモデル.
type securityGroupModel struct {
	Name types.String `tfsdk:"name"`
}

func (r *instanceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_instance"
}

func (r *instanceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages instance resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The UUID of the instance.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			// リクエストパラメータ
			"flavor_id": schema.StringAttribute{
				MarkdownDescription: "The UUID of the flavor. The flavor ID can be obtained from the [ConoHa v3 API](https://doc.conoha.jp/reference/api-vps3/api-compute-vps3/compute-get_flavors_list-v3/?btn_id=reference-compute-get_flavors_detail-v3--sidebar_reference-compute-get_flavors_list-v3). Changing this value will resize the instance.",
				Required:            true,
			},
			"admin_pass": schema.StringAttribute{
				MarkdownDescription: "The administrator password for the instance. If not provided, a random password will be generated by the API. The password must be 9-70 characters long and include at least one uppercase letter, lowercase letter, number, and symbol. Changing this value will force the instance to be recreated.",
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(9, 70),
					stringvalidator.RegexMatches(
						regexp.MustCompile("^[a-zA-Z0-9^$+\\-*/|()\\[\\]{}.,:;?!_=&@~%#'\"\\\\]*$"),
						"Password must contain only alphanumeric characters and the following symbols: ^$+-*/|()[]{}.,:;?!_=&@~%#'\"\\",
					),
					stringvalidator.RegexMatches(
						regexp.MustCompile("[A-Z]"),
						"Password must contain at least one uppercase letter, lowercase letter, number, and symbol.",
					),
					stringvalidator.RegexMatches(
						regexp.MustCompile("[a-z]"),
						"Password must contain at least one uppercase letter, lowercase letter, number, and symbol.",
					),
					stringvalidator.RegexMatches(
						regexp.MustCompile("[0-9]"),
						"Password must contain at least one uppercase letter, lowercase letter, number, and symbol.",
					),
					stringvalidator.RegexMatches(
						regexp.MustCompile("[^a-zA-Z0-9]"),
						"Password must contain at least one uppercase letter, lowercase letter, number, and symbol.",
					),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"block_device": schema.ListNestedAttribute{
				MarkdownDescription: "The block device mapping for the instance: the volumes given when the server is created. " +
					"A volume attached later with `conohavps_volume_attachment` is not listed here, so it does not force the server to be recreated.",
				Required: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"uuid": schema.StringAttribute{
							MarkdownDescription: "The UUID of the volume to attach as a block device.",
							Required:            true,
						},
					},
				},
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
			},
			"security_group": schema.ListNestedAttribute{
				MarkdownDescription: "The security groups to associate with the instance. Changing this value will update the instance's security groups.",
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the security group.",
							Required:            true,
						},
					},
				},
			},
			"key_name": schema.StringAttribute{
				MarkdownDescription: "The name of the SSH key pair. Changing this value will force the instance to be recreated.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"instance_name_tag": schema.StringAttribute{
				MarkdownDescription: "The name tag of the instance. Must be 1-255 characters long and contain only alphanumeric characters, hyphens (-), and underscores (_). Changing this value will update the instance metadata.",
				Required:            true,
				Computed:            false,
				Validators: []validator.String{
					// 文字列長チェック(1～255文字)
					stringvalidator.LengthBetween(1, 255),
					// 利用可能な文字のみを含むかチェック
					stringvalidator.RegexMatches(
						regexp.MustCompile("^[a-zA-Z0-9-_]*$"),
						"The name tag must contain only alphanumeric characters, hyphens (-), and underscores (_).",
					),
				},
			},
			"user_data": schema.StringAttribute{
				MarkdownDescription: "The user data to be made available to the instance. Must be a `base64-encoded string`. Changing this value will force the instance to be recreated.",
				Optional:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"power_state": schema.StringAttribute{
				MarkdownDescription: "The power state of the instance. Valid values are `ACTIVE` or `SHUTOFF`. The instance will be started or stopped to match this state when specified.",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("ACTIVE", "SHUTOFF"),
				},
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "The current status of the instance.",
				Computed:            true,
			},
			"addresses": schema.MapAttribute{
				MarkdownDescription: "The network addresses assigned to the instance.",
				Computed:            true,
				ElementType:         types.ListType{ElemType: types.ObjectType{AttrTypes: addressDetailAttrTypes}},
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *instanceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	conohaClient, ok := req.ProviderData.(*service.ConohaClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected resource configure type",
			fmt.Sprintf("Expected *service.ConohaClient, but got: %T.", req.ProviderData),
		)
		return
	}

	r.client = conohaClient
}

func (r *instanceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan instanceResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Starting instance creation request.", map[string]any{
		"flavor_id":         plan.FlavorRef.ValueString(),
		"instance_name_tag": plan.InstanceNameTag.ValueString(),
		"block_device":      plan.BlockDevice,
		"security_group":    plan.SecurityGroup,
		"key_name":          plan.KeyName.ValueString(),
		"power_state":       plan.PowerState.ValueString(),
		"user_data":         plan.UserData.ValueString(),
	})

	// インスタンス作成用のブロックデバイスマッピング（複数ボリューム対応、UUIDのみ必須）
	var blockDevice []servers.BlockDevice

	if !plan.BlockDevice.IsNull() {
		var bdmList []blockDeviceModel
		diag := plan.BlockDevice.ElementsAs(ctx, &bdmList, false)
		if !diag.HasError() {
			blockDevice = make([]servers.BlockDevice, len(bdmList))
			for i, bdm := range bdmList {
				// UUIDのみ必須、SourceTypeはvolume固定
				blockDevice[i] = servers.BlockDevice{
					SourceType: "volume",
					UUID:       bdm.UUID.ValueString(),
				}
			}
		}
	}

	// メタデータ構築（instance_name_tagはメタデータで管理）
	metadata := make(map[string]string)
	metadata["instance_name_tag"] = plan.InstanceNameTag.ValueString()

	// オプション構築
	opts := make(map[string]interface{})

	if !plan.AdminPass.IsNull() && plan.AdminPass.ValueString() != "" {
		opts["admin_pass"] = plan.AdminPass.ValueString()
		tflog.Debug(ctx, "AdminPass provided in plan.", map[string]any{})
	}

	if !plan.KeyName.IsNull() {
		opts["key_name"] = plan.KeyName.ValueString()
	}

	// セキュリティグループを処理
	if !plan.SecurityGroup.IsNull() {
		var sgList []securityGroupModel
		diag := plan.SecurityGroup.ElementsAs(ctx, &sgList, false)
		if !diag.HasError() {
			sgNames := make([]string, len(sgList))
			for i, sg := range sgList {
				sgNames[i] = sg.Name.ValueString()
			}
			opts["security_groups"] = sgNames
		}
	}

	if len(metadata) > 0 {
		opts["metadata"] = metadata
	}

	if !plan.UserData.IsNull() {
		opts["user_data"] = plan.UserData.ValueString()
	}

	// インスタンスを作成
	instance, err := r.client.CreateInstance(ctx, plan.InstanceNameTag.ValueString(), plan.FlavorRef.ValueString(), blockDevice, opts)
	if err != nil {
		resp.Diagnostics.AddError(
			"Failed to create instance resource",
			"An unexpected error occurred while attempting to create instance resource.\n\n"+
				"Error: "+err.Error(),
		)
		return
	}

	plan.Id = types.StringValue(instance.ID)

	// admin_passを常に設定（指定がない場合はAPIから取得した値を使用）
	if plan.AdminPass.IsNull() || plan.AdminPass.ValueString() == "" {
		plan.AdminPass = types.StringValue(instance.AdminPass)
		tflog.Debug(ctx, "AdminPass set from API response.", map[string]any{})
	} else {
		// ユーザーが指定した場合はそのまま使用（既に opts に設定済み）
		tflog.Debug(ctx, "AdminPass set from user input.", map[string]any{})
	}

	// インスタンスがACTIVEになるまで待機（タイムアウト：10分）
	instance, err = r.client.WaitForInstanceState(ctx, instance.ID, "ACTIVE", 10*time.Minute)
	if err != nil {
		resp.Diagnostics.AddError(
			"Wait timeout exceeded",
			"An unexpected error occurred while waiting for instance resource to become ACTIVE.\n\n"+
				"Error: "+err.Error(),
		)
		return
	}

	tflog.Debug(ctx, "Instance is now ACTIVE.", map[string]any{})

	// power_stateがSHUTOFFの場合、停止処理を実行
	if !plan.PowerState.IsNull() {
		powerState := plan.PowerState.ValueString()
		if powerState == "SHUTOFF" {
			err = r.client.StopInstance(ctx, instance.ID)
			if err != nil {
				resp.Diagnostics.AddError(
					"Failed to stop instance resource",
					"An unexpected error occurred while attempting to stop instance resource.\n\n"+
						"Error: "+err.Error(),
				)
				return
			}

			// SHUTOFFになるまで待機
			_, err = r.client.WaitForInstanceState(ctx, instance.ID, "SHUTOFF", 5*time.Minute)
			if err != nil {
				resp.Diagnostics.AddError(
					"Wait timeout exceeded",
					"An unexpected error occurred while waiting for instance resource to become SHUTOFF.\n\n"+
						"Error: "+err.Error(),
				)
				return
			}
		}
	}

	// インスタンス情報を再取得
	instance, err = r.client.GetInstance(ctx, instance.ID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Failed to read instance resource after instance creation",
			"An unexpected error occurred while attempting to read instance resource.\n\n"+
				"Error: "+err.Error(),
		)
		return
	}

	plan.Status = types.StringValue(instance.Status)

	// Addressesを更新
	r.updateAddressesFromInstance(ctx, &plan, instance)

	tflog.Debug(ctx, "Instance creation request completed.", map[string]any{"id": plan.Id.ValueString()})

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *instanceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state instanceResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Starting instance read request.", map[string]any{})

	// インスタンス情報を取得
	instance, err := r.client.GetInstance(ctx, state.Id.ValueString())
	if err != nil {
		if gophercloud.ResponseCodeIs(err, 404) {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError(
			"Failed to read instance resource",
			"An unexpected error occurred while attempting to read instance resource.\n\n"+
				"Error: "+err.Error(),
		)
		return
	}

	state.Status = types.StringValue(instance.Status)

	// Flavor IDを抽出
	flavorID, ok := instance.Flavor["id"].(string)
	if !ok {
		tflog.Error(ctx, "Failed to extract flavor ID.", map[string]any{
			"instance_id": state.Id.ValueString(),
			"flavor":      instance.Flavor,
		})
		return
	}

	state.FlavorRef = types.StringValue(flavorID)
	state.InstanceNameTag = types.StringValue(instance.Metadata["instance_name_tag"])

	// AdminPassはCreate時のみ返却される
	if state.AdminPass.IsNull() {
		state.AdminPass = types.StringValue(instance.AdminPass)
	}

	// ブロックデバイス情報を更新.
	// サーバーに付いているボリュームのうち、この設定で作成時に渡したものだけを写す.
	// conohavps_volume_attachment で後から付けた追加 SSD まで写すと block_device に差分が出て、サーバーが作り直しになる
	var declared []string
	if !state.BlockDevice.IsNull() {
		var bdmList []blockDeviceModel
		if diag := state.BlockDevice.ElementsAs(ctx, &bdmList, false); !diag.HasError() {
			for _, bdm := range bdmList {
				declared = append(declared, bdm.UUID.ValueString())
			}
		}
	}
	attached := make([]string, 0, len(instance.AttachedVolumes))
	for _, v := range instance.AttachedVolumes {
		attached = append(attached, v.ID)
	}
	kept := keepDeclaredBlockDevices(declared, attached)
	blockDevices := make([]attr.Value, len(kept))
	for i, id := range kept {
		bdObj, _ := types.ObjectValue(
			map[string]attr.Type{
				"uuid": types.StringType,
			},
			map[string]attr.Value{
				"uuid": types.StringValue(id),
			},
		)
		blockDevices[i] = bdObj
	}

	state.BlockDevice, _ = types.ListValue(
		types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"uuid": types.StringType,
			},
		},
		blockDevices,
	)

	r.updateAddressesFromInstance(ctx, &state, instance)

	if !state.KeyName.IsNull() {
		state.KeyName = types.StringValue(instance.KeyName)
	}

	if !state.PowerState.IsNull() {
		if instance.Status == "ACTIVE" || instance.Status == "SHUTOFF" {
			state.PowerState = types.StringValue(instance.Status)
		}
	}

	tflog.Debug(ctx, "Instance read request completed.", map[string]any{})

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *instanceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan instanceResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Starting instance update request.", map[string]any{
		"instance_id":       plan.Id.ValueString(),
		"flavor_id":         plan.FlavorRef.ValueString(),
		"instance_name_tag": plan.InstanceNameTag.ValueString(),
		"security_group":    plan.SecurityGroup,
		"power_state":       plan.PowerState.ValueString(),
	})

	var state instanceResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// flavor_idが変更された場合の処理（先に実行）
	// resizeによってインスタンスが停止されるため、power_stateの変更処理より先に実行する必要がある
	flavorChanged := !plan.FlavorRef.Equal(state.FlavorRef)
	if flavorChanged {
		tflog.Debug(ctx, "flavor_id change detected, handling flavor change.", map[string]any{"from": state.FlavorRef.ValueString(), "to": plan.FlavorRef.ValueString()})

		err := r.handleFlavorChange(ctx, plan.Id.ValueString(), plan.FlavorRef.ValueString())
		if err != nil {
			resp.Diagnostics.AddError(
				"Failed to process flavor change",
				"An unexpected error occurred while processing flavor change.\n\n"+
					"Error: "+err.Error(),
			)
			return
		}

		tflog.Debug(ctx, "Changing flavor_id completed.", map[string]any{})
	}

	// power_stateが変更された場合の処理（resize後に実行）
	// power_stateがACTIVEの場合、resizeで停止されたインスタンスを、ここで起動する
	if !plan.PowerState.Equal(state.PowerState) {
		tflog.Debug(ctx, "power_state change detected, handling power state change.", map[string]any{"from": state.PowerState.ValueString(), "to": plan.PowerState.ValueString()})

		err := r.handlePowerStateChange(ctx, plan.Id.ValueString(), plan.PowerState.ValueString())
		if err != nil {
			resp.Diagnostics.AddError(
				"Failed to process power state change",
				"An unexpected error occurred while processing power state change.\n\n"+
					"Error: "+err.Error(),
			)
			return
		}

		tflog.Debug(ctx, "Changing power_state completed.", map[string]any{})
	} else if flavorChanged {
		// flavor_idが変更された場合、resizeによってインスタンスは必ずSHUTOFF状態になる
		// Plan で power_state が指定されている場合、その値に復帰させる必要がある
		tflog.Debug(ctx, "flavor_id changed, checking power_state to restore.", map[string]any{})

		if !plan.PowerState.IsNull() && plan.PowerState.ValueString() == "ACTIVE" {
			// Plan で ACTIVE を指定している場合、起動処理を実行
			err := r.handlePowerStateChange(ctx, plan.Id.ValueString(), plan.PowerState.ValueString())
			if err != nil {
				resp.Diagnostics.AddError(
					"Failed to restore power_state",
					"An unexpected error occurred while attempting to restore power_state.\n\n"+
						"Error: "+err.Error(),
				)
				return
			}
		}

		tflog.Debug(ctx, "Restoring power_state completed after flavor change.", map[string]any{})
	}

	// instance_name_tagが変更された場合の処理
	if !plan.InstanceNameTag.Equal(state.InstanceNameTag) {
		tflog.Debug(ctx, "instance_name_tag change detected, updating metadata.", map[string]any{"from": state.InstanceNameTag.ValueString(), "to": plan.InstanceNameTag.ValueString()})

		metadata := make(map[string]string)
		metadata["instance_name_tag"] = plan.InstanceNameTag.ValueString()

		err := r.client.UpdateInstanceMetadata(ctx, plan.Id.ValueString(), metadata)
		if err != nil {
			resp.Diagnostics.AddError(
				"Failed to update instance_name_tag",
				"An unexpected error occurred while attempting to update instance_name_tag.\n\n"+
					"Error: "+err.Error(),
			)
			return
		}

		tflog.Debug(ctx, "Updating instance_name_tag completed.", map[string]any{})
	}

	// security_groupが変更された場合の処理
	if !plan.SecurityGroup.Equal(state.SecurityGroup) {
		tflog.Debug(ctx, "security_group change detected, updating security groups.", map[string]any{"from": state.SecurityGroup, "to": plan.SecurityGroup})

		var sgList []securityGroupModel

		diag := plan.SecurityGroup.ElementsAs(ctx, &sgList, false)
		if !diag.HasError() {
			// SecurityGroupUpdate配列を構築
			var sgUpdates []service.SecurityGroupUpdate

			if len(sgList) == 0 {
				sgUpdates = make([]service.SecurityGroupUpdate, 1)
				sgUpdates[0] = service.SecurityGroupUpdate{
					Name: "default",
				}
			} else {
				sgUpdates = make([]service.SecurityGroupUpdate, len(sgList))
				for i, sg := range sgList {
					sgUpdates[i] = service.SecurityGroupUpdate{
						Name: sg.Name.ValueString(),
					}
				}
			}

			err := r.client.UpdateInstanceSecurityGroups(ctx, plan.Id.ValueString(), sgUpdates)
			if err != nil {
				resp.Diagnostics.AddError(
					"Failed to update security_group",
					"An unexpected error occurred while attempting to update security_group.\n\n"+
						"Error: "+err.Error(),
				)
				return
			}
		}

		tflog.Debug(ctx, "Updating security_group completed.", map[string]any{})
	}

	// インスタンス情報を再取得
	instance, err := r.client.GetInstance(ctx, plan.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Failed to read instance resource",
			"An unexpected error occurred while attempting to read instance resource.\n\n"+
				"Error: "+err.Error(),
		)
		return
	}

	tflog.Debug(ctx, "Instance update request completed.", map[string]any{
		"id": plan.Id.ValueString(),
	})

	// Statusを更新
	plan.Status = types.StringValue(instance.Status)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *instanceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state instanceResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Starting instance deletion request.", map[string]any{
		"instance_id": state.Id.ValueString(),
	})

	// インスタンスを削除
	err := r.client.DeleteInstance(ctx, state.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Failed to delete instance resource",
			"An unexpected error occurred while attempting to delete instance resource.\n\n"+
				"Error: "+err.Error(),
		)
		return
	}

	tflog.Debug(ctx, "Instance deletion request completed.", map[string]any{
		"id": state.Id.ValueString(),
	})
}

func (r *instanceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// ヘルパー関数：Addressesのみを更新.
func (r *instanceResource) updateAddressesFromInstance(ctx context.Context, data *instanceResourceModel, instance interface{}) {
	server, ok := instance.(*servers.Server)
	if !ok {
		tflog.Error(ctx, "Type assertion failed: servers.Server.", map[string]any{
			"received_type": fmt.Sprintf("%T", instance),
		})
		return
	}

	// Addressesの処理（ネットワークアドレス情報）
	addressMapValues := make(map[string]attr.Value)
	if len(server.Addresses) > 0 {
		for netName, addrs := range server.Addresses {
			if addrSlice, ok := addrs.([]interface{}); ok && len(addrSlice) > 0 {
				addrObjects := make([]attr.Value, len(addrSlice))
				for i, addr := range addrSlice {
					if addrMap, ok := addr.(map[string]interface{}); ok {
						addrValue := ""
						if a, ok := addrMap["addr"]; ok {
							addrValue = fmt.Sprintf("%v", a)
						}
						version := int64(0)
						if v, ok := addrMap["version"]; ok {
							if vf, ok := v.(float64); ok {
								version = int64(vf)
							}
						}
						osExtIPSType := ""
						if t, ok := addrMap["OS-EXT-IPS:type"]; ok {
							osExtIPSType = fmt.Sprintf("%v", t)
						}
						osExtIPSMACAddr := ""
						if m, ok := addrMap["OS-EXT-IPS-MAC:mac_addr"]; ok {
							osExtIPSMACAddr = fmt.Sprintf("%v", m)
						}

						// addressDetailAttrTypesを使用してObjectValueを構築
						addrObj, _ := types.ObjectValue(
							addressDetailAttrTypes,
							map[string]attr.Value{
								"addr":                types.StringValue(addrValue),
								"version":             types.Int64Value(version),
								"os_ext_ips_type":     types.StringValue(osExtIPSType),
								"os_ext_ips_mac_addr": types.StringValue(osExtIPSMACAddr),
							},
						)
						addrObjects[i] = addrObj
					}
				}

				// addressDetailAttrTypesを再利用してListValueを構築
				addrList, _ := types.ListValue(
					types.ObjectType{
						AttrTypes: addressDetailAttrTypes,
					},
					addrObjects,
				)
				addressMapValues[netName] = addrList
			}
		}

		if len(addressMapValues) > 0 {
			// addressDetailAttrTypesを再利用してMapValueを構築
			addresses, _ := types.MapValue(
				types.ListType{ElemType: types.ObjectType{AttrTypes: addressDetailAttrTypes}},
				addressMapValues,
			)
			data.Addresses = addresses
		}
	}

	tflog.Debug(ctx, "Addresses updated in State.", map[string]any{
		"instance_id":     server.ID,
		"addresses_count": len(addressMapValues),
	})
}

// ヘルパー関数：フレーバー変更処理.
func (r *instanceResource) handleFlavorChange(ctx context.Context, instanceID string, flavorRef string) error {
	// インスタンスの現在の状態を確認
	instance, err := r.client.GetInstance(ctx, instanceID)
	if err != nil {
		return fmt.Errorf("failed to retrieve instance status: %w", err)
	}

	// SHUTOFF状態でなければ停止
	if instance.Status != "SHUTOFF" {
		err := r.client.StopInstance(ctx, instanceID)
		if err != nil {
			return fmt.Errorf("failed to stop instance: %w", err)
		}

		_, err = r.client.WaitForInstanceState(ctx, instanceID, "SHUTOFF", 5*time.Minute)
		if err != nil {
			return fmt.Errorf("failed to wait for instance to stop: %w", err)
		}
	}

	// リサイズを実行
	err = r.client.ResizeInstance(ctx, instanceID, flavorRef)
	if err != nil {
		return fmt.Errorf("failed to resize instance: %w", err)
	}

	// リサイズ完了を待機
	_, err = r.client.WaitForInstanceState(ctx, instanceID, "VERIFY_RESIZE", 10*time.Minute)
	if err != nil {
		revertErr := r.client.RevertResizeInstance(ctx, instanceID)
		if revertErr != nil {
			tflog.Error(ctx, "Failed to revert resize.", map[string]any{
				"instance_id": instanceID,
				"error":       revertErr.Error(),
			})
			return fmt.Errorf("failed to wait for resize verification: %w (failed to revert resize: %w)", err, revertErr)
		}
		return fmt.Errorf("failed to wait for resize verification: %w", err)
	}

	// リサイズを確定
	err = r.client.ConfirmResizeInstance(ctx, instanceID)
	if err != nil {
		return fmt.Errorf("failed to confirm resize: %w", err)
	}

	// 確定後、SHUTOFF状態になるまで待機
	_, err = r.client.WaitForInstanceState(ctx, instanceID, "SHUTOFF", 10*time.Minute)
	if err != nil {
		return fmt.Errorf("failed to wait for instance to become SHUTOFF after resize: %w", err)
	}

	tflog.Debug(ctx, "Flavor changed successfully.", map[string]any{
		"instance_id": instanceID,
		"new_flavor":  flavorRef,
	})

	return nil
}

// ヘルパー関数：電源状態変更処理.
func (r *instanceResource) handlePowerStateChange(ctx context.Context, instanceID string, desiredPowerState string) error {
	instance, err := r.client.GetInstance(ctx, instanceID)
	if err != nil {
		return fmt.Errorf("failed to retrieve instance information: %w", err)
	}
	currentPowerState := instance.Status

	// 既に目的の状態であればスキップ
	if currentPowerState == desiredPowerState {
		tflog.Debug(ctx, "Power state is already in desired state.", map[string]any{
			"instance_id": instanceID,
			"state":       desiredPowerState,
		})
		return nil
	}

	// ACTIVEに変更
	if desiredPowerState == "ACTIVE" {
		if currentPowerState != "ACTIVE" {
			tflog.Debug(ctx, "Starting instance.", map[string]any{
				"instance_id":   instanceID,
				"current_state": currentPowerState,
			})

			// レースコンディション対策として再度状態確認
			latestInstance, err := r.client.GetInstance(ctx, instanceID)
			if err != nil {
				return fmt.Errorf("failed to retrieve latest instance status: %w", err)
			}

			if latestInstance.Status == "ACTIVE" {
				tflog.Debug(ctx, "Instance is already ACTIVE.", map[string]any{
					"instance_id": instanceID,
				})
				return nil
			}

			err = r.client.StartInstance(ctx, instanceID)
			if err != nil {
				return fmt.Errorf("failed to start instance: %w", err)
			}

			_, err = r.client.WaitForInstanceState(ctx, instanceID, "ACTIVE", 10*time.Minute)
			if err != nil {
				return fmt.Errorf("failed to wait for instance to become ACTIVE: %w", err)
			}

			tflog.Debug(ctx, "Instance started successfully.", map[string]any{
				"instance_id": instanceID,
			})
		}
	}

	// SHUTOFFに変更
	if desiredPowerState == "SHUTOFF" {
		if currentPowerState != "SHUTOFF" {
			tflog.Debug(ctx, "Stopping instance.", map[string]any{
				"instance_id":   instanceID,
				"current_state": currentPowerState,
			})

			// レースコンディション対策として再度状態確認
			latestInstance, err := r.client.GetInstance(ctx, instanceID)
			if err != nil {
				return fmt.Errorf("failed to retrieve latest instance status: %w", err)
			}

			if latestInstance.Status == "SHUTOFF" {
				tflog.Debug(ctx, "Instance is already SHUTOFF.", map[string]any{
					"instance_id": instanceID,
				})
				return nil
			}

			err = r.client.StopInstance(ctx, instanceID)
			if err != nil {
				return fmt.Errorf("failed to stop instance: %w", err)
			}

			_, err = r.client.WaitForInstanceState(ctx, instanceID, "SHUTOFF", 10*time.Minute)
			if err != nil {
				return fmt.Errorf("failed to wait for instance to become SHUTOFF: %w", err)
			}

			tflog.Debug(ctx, "Instance stopped successfully.", map[string]any{
				"instance_id": instanceID,
			})
		}
	}

	return nil
}

// keepDeclaredBlockDevices は、サーバーに付いているボリューム（attached）のうち state の block_device に挙がっているもの（declared）だけを
// state の順序で返す. state に無いもの（conohavps_volume_attachment で付けた追加 SSD）は写さない.
// state が空（import 直後）なら、付いているものを全部返す.
func keepDeclaredBlockDevices(declared, attached []string) []string {
	if len(declared) == 0 {
		return attached
	}
	isAttached := make(map[string]bool, len(attached))
	for _, id := range attached {
		isAttached[id] = true
	}
	kept := make([]string, 0, len(declared))
	for _, id := range declared {
		if isAttached[id] {
			kept = append(kept, id)
		}
	}
	return kept
}
