name: Tests

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'gmo-internet/priv_terraform-provider-conohavps'
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  test:
    if: github.repository == 'gmo-internet/priv_terraform-provider-conohavps'
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.14.5'
          terraform_wrapper: false
      - run: go mod download
      - run: go test -v -timeout 60m ./...
        timeout-minutes: 75
        env:
          TF_ACC: "1"
          CONOHAVPS_IDENTITY_ENDPOINT: ${{ secrets.CONOHAVPS_IDENTITY_ENDPOINT }}
          CONOHAVPS_PASSWORD: ${{ secrets.CONOHAVPS_PASSWORD }}
          CONOHAVPS_REGION: ${{ secrets.CONOHAVPS_REGION }}
          CONOHAVPS_TENANT_ID: ${{ secrets.CONOHAVPS_TENANT_ID }}
          CONOHAVPS_USER_ID: ${{ secrets.CONOHAVPS_USER_ID }}

